spring:
  application:
    name: login

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: malldbuser
    password: 
    url: jdbc:mariadb://localhost:3306/malldb

    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 10000

  thymeleaf:
    cache: false

  servlet:
    multipart:
      enabled: true
      location: D:\upload
      max-file-size: 2MB
      max-request-size: 20MB



logging:
  level:
    com.zaxxer: info
    org.springframework.jdbc: info
    org.springframework.security: info
    org:
      apache:
        ibatis:  debug

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.example.login.**.dto

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

board:
  upload: D:\upload\attach


